### ISSUE TITLE
ds setting auth results in "User account or DS host info missing"

### ISSUE THREAD

**Issue by tooh** [JinnLynn/alfred-workflows#2]
When I try to set usr and pw and host I tried several combinations (IP nr and my synology.me DDNS).

When I use IP nr I get no error and no notification.

But when I try one of the other commands I get:
"User account or DS host info missing"

Where can I find the config file where these settings are stored so I can debug and try to set the config manual ?

As extra info I can note that for reasons of portforwarding Diskstation is running on a different port then 5001.

**Comment by JinnLynn** [comment]
ds host address must include port, e.g. 
http://192.168.0.1:5001
https://192.168.0.1:5001
http://some.synology.me:5001

config file path:  ~/Library/Application Support/Alfred 2/Workflow Data/config.json

**Comment by tooh** [comment]
OK, It works now, but actually the config path is:

~/Library/Application support/Alfred 2/Workflow data/net.jeeker.awf.DownloadStation/config.json

**Comment by JinnLynn** [comment]
thanks, it's my mistake.
